added execption handling and logging for building docker images

diff --git a/.github/workflows/build-service-images-on-trigger.yml b/.github/workflows/build-service-images-on-trigger.yml
--- a/.github/workflows/build-service-images-on-trigger.yml
+++ b/.github/workflows/build-service-images-on-trigger.yml
@@ -30,11 +30,17 @@ jobs:
                     if [[ "$docker_image_name" != "create-missile-obj-dtma" ]]; then
                     
                       echo "Building $docker_image_name"
-                      docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$docker_image_name:latest $dir_of_image --push
+                      docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$docker_image_name:latest $dir_of_image --push || echo "Failed to build $docker_image_name" >> build.log
 
                     fi
                     
                 done;
+            
+            - name: Upload log
+              uses: actions/upload-artifact@v2
+              with:
+                name: build-log
+                path: build.log
 
 
 
